#! /bin/sh

sxhkd &
compton &
polybar bar &

feh --bg-scale ~/Desktop/IHZOAv3.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           10

bspc config top_padding		300
bspc config bottom_padding	300
bspc config left_padding	300
bspc config right_padding	300

bspc config split_ratio          0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
